(() => {
  "use strict";

  const workProjects = [
    {
      slug: "echoes",
      number: "01",
      title: "ECHOES OF SILENCE",
      year: "2026",
      technology: "DIGITAL COMPOSITION",
      category: "VISUAL",
      description: "A quiet study of fragmented light and incomplete coordinates, composed as an editorial image field.",
      previewType: "image",
      embedUrl: "./assets/echoes-DGZS_zVb.png",
      detailUrl: "./project.html?slug=echoes",
      accent: "#a9acb4",
    },
    {
      slug: "floworb",
      number: "02",
      title: "FLOWORB",
      year: "2026",
      technology: "CANVAS / SIMPLEX NOISE",
      category: "MOTION",
      description: "A blue-cyan noise field gathers into a breathing digital volume whose surface continuously folds and reforms.",
      previewType: "iframe",
      embedUrl: "./floworb.html?embed=1&instance=works&controls=hidden",
      detailUrl: "./project.html?slug=floworb",
      accent: "#1e78ff",
    },
    {
      slug: "wave-physics",
      number: "03",
      title: "WAVE PHYSICS LOADER",
      shortTitle: "WAVE PHYSICS",
      year: "2026",
      technology: "CANVAS / PHYSICS",
      category: "SIMULATION",
      description: "Designed cosine waves and restrained physical residuals carry a bouncing body across responsive columns.",
      previewType: "iframe",
      embedUrl: "./wave-physics-loader.html?embed=1&instance=works&theme=light",
      detailUrl: "./project.html?slug=wave-physics",
      accent: "#111111",
    },
    {
      slug: "particle-rubik",
      number: "04",
      title: "PARTICLE RUBIK",
      year: "2026",
      technology: "THREE.JS / WEBGL",
      category: "GENERATIVE",
      description: "A monochrome particle volume surrounds a continuously turning 3×3×3 cube. Spatial noise resolves into a seamless loop.",
      previewType: "iframe",
      embedUrl: "./particle-rubik/index.html?instance=works",
      detailUrl: "./project.html?slug=particle-rubik",
      accent: "#0a0a0a",
    },
    {
      slug: "spectra",
      number: "05",
      title: "SPECTRA",
      year: "2026",
      technology: "WEBGL / GLSL",
      category: "MATERIAL",
      description: "One responsive liquid material explored through six chromatic identities, from soft warmth to electric contrast.",
      previewType: "iframe",
      embedUrl: "./spectra-card/index.html?embed=1",
      detailUrl: "./project.html?slug=spectra",
      accent: "#ff6a7e",
    },
    {
      slug: "archive",
      number: "06",
      title: "THE ARCHIVE",
      year: "2026",
      technology: "CANVAS PARTICLE SYSTEM",
      category: "SYSTEM",
      description: "A geometric object reconstructed from incomplete coordinates, shifting between certainty, memory and simulation.",
      previewType: "iframe",
      embedUrl: "./particle-cube.html",
      detailUrl: "./project.html?slug=archive",
      accent: "#62656c",
    },
  ];

  const skillProjects = [
    {
      slug: "wormhole-admin",
      number: "01",
      title: "WORMHOLE ADMIN UPLOAD",
      shortTitle: "WORMHOLE ADMIN",
      year: "2026",
      technology: "WINDOWS / DATA PIPELINE",
      category: "DATA IO",
      filters: ["interaction", "system"],
      description: "Reads product folders, maps SKU data and validates media, price and inventory in one controlled upload workflow.",
      previewType: "component",
      component: "wormhole",
      detailUrl: "./project.html?slug=wormhole-admin",
      accent: "#111111",
    },
    { ...workProjects[1], number: "02", filters: ["visual", "generative"] },
    { ...workProjects[2], number: "03", filters: ["visual", "simulation"] },
    {
      slug: "fluid-dropdown",
      number: "04",
      title: "FLUID DROPDOWN",
      year: "2026",
      technology: "VUE 3 / UI INPUT",
      category: "UI / INPUT",
      filters: ["interaction", "system"],
      description: "A compact input study with fluid reveal motion, magnetic response and complete keyboard navigation.",
      previewType: "component",
      component: "fluid-dropdown",
      detailUrl: "./project.html?slug=fluid-dropdown",
      accent: "#111111",
    },
    { ...workProjects[4], number: "05", filters: ["visual", "generative"] },
    { ...workProjects[5], number: "06", filters: ["visual", "generative", "system"] },
  ];

  const spectraProjects = [
    ["spectra-original", "01", "ORIGINAL", "./spectra-card/index.html?embed=1", ["#ff6a7e", "#ff8665", "#ffc2cf"]],
    ["spectra-ocean", "02", "OCEAN", "./spectra-card/spectra-blue.html?embed=1", ["#3157ff", "#37d7d2", "#8265ff"]],
    ["spectra-klein", "03", "KLEIN", "./spectra-card/spectra-klein.html?embed=1", ["#f05a18", "#070b13", "#173eae"]],
    ["spectra-ultraviolet", "04", "ULTRAVIOLET", "./spectra-card/spectra-violet-lime.html?embed=1", ["#858ae3", "#613dc1", "#d7f204"]],
    ["spectra-chrome", "05", "CHROME", "./spectra-card/spectra-chrome.html?embed=1", ["#151922", "#a8adb7", "#f4f4f6"]],
    ["spectra-plus", "06", "PLUS", "./spectra-card/spectra-plus.html?embed=1", ["#ff335b", "#ff7a21", "#f6c431"]],
  ].map(([slug, number, title, embedUrl, palette]) => ({
    slug,
    number,
    title,
    year: "2026",
    technology: "WEBGL / GLSL",
    category: "CHROMATIC MATERIAL",
    description: `${title} treats color as a living system: a responsive fluid surface that keeps folding, breathing and reorganising in real time.`,
    previewType: "iframe",
    embedUrl,
    detailUrl: `./project.html?slug=${slug}`,
    palette,
    accent: palette[0],
  }));

  const projectIndex = {};
  [...workProjects, ...skillProjects, ...spectraProjects].forEach((project) => {
    projectIndex[project.slug] = project;
  });

  window.AICreativeLabData = Object.freeze({
    workProjects: Object.freeze(workProjects),
    skillProjects: Object.freeze(skillProjects),
    spectraProjects: Object.freeze(spectraProjects),
    projectIndex: Object.freeze(projectIndex),
    skillFilters: Object.freeze(["all", "visual", "simulation", "interaction", "generative", "system"]),
  });
})();
